# Generated by Django 5.1.2 on 2024-11-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_remove_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
