# Generated by Django 5.1.2 on 2024-11-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('CreateView', 'Can Create'), ('UpdateView', 'Can Update'), ('DeleteView', 'Can Delete')]},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
    ]
